/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswap from "./uniswap";
export type { uniswap };
export type { ACDMToken } from "./ACDMToken";
export type { Platform } from "./Platform";
export type { Staking } from "./Staking";
export type { Voting } from "./Voting";
export type { XXXToken } from "./XXXToken";
